name = "bowen"
version = "0.1.0"
defaultTargets = ["bowen"]

[[lean_lib]]
name = "Bowen"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.15.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"
